### ISSUE TITLE
404 error loading angular-split using systemjs

### ISSUE THREAD

**Issue by jitsmaster** [bertrandg/angular-split#3]
I use systemjs for load node module, can't have angulars-split working.

Got following runtime error:

```
zone.js:232 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost/cmstrunk/angular-split
	Error: XHR error (404 Not Found) loading http://localhost/cmstrunk/angular-split
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost/CMStrunk/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost/CMStrunk/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost/CMStrunk/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost/CMStrunk/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost/cmstrunk/angular-split as "angular-split" from http://localhost/cmstrunk/js/ngWidgets/igxroot.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost/CMStrunk/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost/CMStrunk/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost/CMStrunk/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost/CMStrunk/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost/cmstrunk/angular-split as "angular-split" from 
```

localhost/cmstrunk is the app url.

AOT compile run into following error:

```
[08:49:15] Error: Command failed: "node_modules\.bin\ngc" -p tsconfig.json
can't resolve module D:/ProductDev_TF/CMS_Trunk/CMS_Site/node_modules/angular-split/node_modules/@angular/core/src/di/reflective_key.d.ts from D:/Prod
uctDev_TF/CMS_Trunk/CMS_Site/node_modules/angular-split/node_modules/@angular/core/src/di/reflective_key.d.ts
Error: can't find symbol KeyRegistry exported from module D:/ProductDev_TF/CMS_Trunk/CMS_Site/node_modules/angular-split/node_modules/@angular/core/sr
c/di/reflective_key.d.ts
    at ReflectorHost.findDeclaration (D:\ProductDev_TF\CMS_Trunk\CMS_Site\node_modules\@angular\compiler-cli\src\reflector_host.js:173:23)
    at D:\ProductDev_TF\CMS_Trunk\CMS_Site\node_modules\@angular\compiler-cli\src\codegen.js:137:46
    at Array.forEach (native)
    at extractProgramSymbols (D:\ProductDev_TF\CMS_Trunk\CMS_Site\node_modules\@angular\compiler-cli\src\codegen.js:120:10)
    at CodeGenerator.codegen (D:\ProductDev_TF\CMS_Trunk\CMS_Site\node_modules\@angular\compiler-cli\src\codegen.js:57:29)
    at codegen (D:\ProductDev_TF\CMS_Trunk\CMS_Site\node_modules\@angular\compiler-cli\src\main.js:7:81)
    at Object.main (D:\ProductDev_TF\CMS_Trunk\CMS_Site\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (D:\ProductDev_TF\CMS_Trunk\CMS_Site\node_modules\@angular\compiler-cli\src\main.js:16:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
Compilation failed

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

I am using version 0.1.15

Any help is appreciated.

Arnold

**Comment by bertrandg** [comment]
hi @jitsmaster ,

Take a look at this plunker using systemjs:
https://plnkr.co/edit/tEjcXo?p=preview

Try with this config:
```js
System.config({
  ...
  map: {
    ...
    'angular-split': 'node_modules/angular-split/dist/index.js'
  },
  ...
  }
});```

What's you angular version?

**Comment by jitsmaster** [comment]
That is very dumb of me not to remember to change systemjs config.

Now none AOT working fine.

I am still getting same error on AOT.

Thank you very much for responding so quickly.

**Comment by jitsmaster** [comment]
AOT issue is also my mistake. My main app is still using Angular 2.3. Sorry for the false alerts for this whole issue.

**Comment by bertrandg** [comment]
No problem, happy to see people using it! :)

**Comment by bertrandg** [comment]
@jitsmaster I added systemjs config to the website: 
https://bertrandg.github.io/angular-split/#/

Do you know that the new "official" way to bundle app is using **angular-cli** (which use **webpack** under the hood)?
That's easier to bundle app and generate production files.

**Comment by jitsmaster** [comment]
Thank you. I use cli for my new projects. This project I am using split on is quite old and has 2 versions of dojo toolkit in it too. Webpack cannot work with those frameworks. 

Appreciate all your hep
